server:
  port: 8080
  servlet:
    context-path: /api/
    application-display-name: expensetrackerapi

spring:
  application:
    name: expensetrackerapi
  datasource:
    # MYSQL
    # url: jdbc:mysql://localhost:33060/expensetracker?reconnect=true
    # username: root
    # password: root
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # initialize: false
    # PostGresql
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialize: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect

#  thymeleaf:
#    cache: false
#  flyway:
#    enabled: true
#    clean-disabled: false
#    clean-on-validation-error: false
#    locations: classpath:/db/migration/schema, classpath:/db/migration/data/dev
#    table: schema_history
#logging:
#  level:
#    com.mkyong: DEBUG
#    org:
#      hibernate:
#        SQL: INFO
#      springframework:
#        web: ERROR
#  #path: /var/log/expensetrackerapi
#
#
#Appenders:
#  File:
#    name: File_Appender
#    fileName: logfile.log
#    PatternLayout:
#      Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#
#
#jwt:
#  secret: mysecret
#
##Swagger Properties
##http://localhost:8095/api/swagger-ui.html#/jwt-authentication-controller
#swagger:
#  api:
#    title: App-Swagger2-Demo
#    description: Swagger Demo
#    termsOfServiceUrl: http://blog.anishpanthi.net
#    version: 1.0
#    controller:
#      basepackage: com.expensetrackerapi.controller
#
#corsallowedOrigins: http://localhost:4200
#
#
jwt:
  secret: que_onda_wey