server:
  port: 5000
  servlet:
    context-path: /api/
    application-display-name: expensetrackerapi

spring:
  application:
    name: expensetrackerapi
  datasource:
    # MYSQL
    url: jdbc:mysql://expensetracker.cgoc02rqrfkn.us-east-2.rds.amazonaws.com:3306/expensetracker
    username: root
    password: Jhona9090
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  secret: que_onda_wey