version: "3.3"

services:
  db:
    image: mysql:8
    container_name: 'expensetracker-mysql'
    ports:
        - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: expensetracker
    volumes:
      - $PWD/migrations:/docker-entrypoint-initdb.d
  #beautymakeup-springboot:
  #  image: beautymakeup-springboot
   # depends_on:
     # - db
    #ports:
      #- 8095:8080

